apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: u66py9ix0-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u66py9ix0-python 
  name: u66py9ix0-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: u66py9ix0-python
    weight: 100 
