apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u66py9ix0-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u66py9ix0-python 
  name: u66py9ix0-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u66py9ix0-python 
